language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t spring-boot-docker -f Dockerfile .

script:
  - docker run -e CI=true spring-boot-docker java -jar spring-boot-docker.jar
