version: "3"
services:
  spring-boot-docker:
    image: spring-boot-docker
    ports:
      - "8080:8080"
    networks:
      - spring-boot-docker-mysql
    depends_on:
      - mysqldb
 
  mysqldb:
    image: mysql:8
    networks:
      - spring-boot-docker-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=bootdb  

networks:
  spring-boot-docker-mysql: