spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bootdb
    username: root
    password: root
    platform: mysql
    driverClassName: com.mysql.cj.jdbc.Driver
    initialization-mode: always
  application:
    name: 'spring-boot-docker'
    
server:
  port: 8080 
