spring:
  datasource:
    url: jdbc:mysql://localhost/bootdb
    username: root
    password: root
    platform: mysql
    initialization-mode: always
  application:
    name: 'spring-boot-docker'
    
server:
  port: 8080 
